/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeaponsIndexRouteImport } from './routes/weapons.index'
import { Route as SquadronsIndexRouteImport } from './routes/squadrons.index'
import { Route as NationsIndexRouteImport } from './routes/nations.index'
import { Route as ConflictsIndexRouteImport } from './routes/conflicts.index'
import { Route as AircraftIndexRouteImport } from './routes/aircraft.index'
import { Route as AcesIndexRouteImport } from './routes/aces.index'
import { Route as WeaponsIdRouteImport } from './routes/weapons.$id'
import { Route as SquadronsIdRouteImport } from './routes/squadrons.$id'
import { Route as NationsIdRouteImport } from './routes/nations.$id'
import { Route as ConflictsIdRouteImport } from './routes/conflicts.$id'
import { Route as AircraftIdRouteImport } from './routes/aircraft.$id'
import { Route as AcesIdRouteImport } from './routes/aces.$id'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeaponsIndexRoute = WeaponsIndexRouteImport.update({
  id: '/weapons/',
  path: '/weapons/',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadronsIndexRoute = SquadronsIndexRouteImport.update({
  id: '/squadrons/',
  path: '/squadrons/',
  getParentRoute: () => rootRouteImport,
} as any)
const NationsIndexRoute = NationsIndexRouteImport.update({
  id: '/nations/',
  path: '/nations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsIndexRoute = ConflictsIndexRouteImport.update({
  id: '/conflicts/',
  path: '/conflicts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AircraftIndexRoute = AircraftIndexRouteImport.update({
  id: '/aircraft/',
  path: '/aircraft/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcesIndexRoute = AcesIndexRouteImport.update({
  id: '/aces/',
  path: '/aces/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeaponsIdRoute = WeaponsIdRouteImport.update({
  id: '/weapons/$id',
  path: '/weapons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadronsIdRoute = SquadronsIdRouteImport.update({
  id: '/squadrons/$id',
  path: '/squadrons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NationsIdRoute = NationsIdRouteImport.update({
  id: '/nations/$id',
  path: '/nations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsIdRoute = ConflictsIdRouteImport.update({
  id: '/conflicts/$id',
  path: '/conflicts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AircraftIdRoute = AircraftIdRouteImport.update({
  id: '/aircraft/$id',
  path: '/aircraft/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AcesIdRoute = AcesIdRouteImport.update({
  id: '/aces/$id',
  path: '/aces/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/aces/$id': typeof AcesIdRoute
  '/aircraft/$id': typeof AircraftIdRoute
  '/conflicts/$id': typeof ConflictsIdRoute
  '/nations/$id': typeof NationsIdRoute
  '/squadrons/$id': typeof SquadronsIdRoute
  '/weapons/$id': typeof WeaponsIdRoute
  '/aces/': typeof AcesIndexRoute
  '/aircraft/': typeof AircraftIndexRoute
  '/conflicts/': typeof ConflictsIndexRoute
  '/nations/': typeof NationsIndexRoute
  '/squadrons/': typeof SquadronsIndexRoute
  '/weapons/': typeof WeaponsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/aces/$id': typeof AcesIdRoute
  '/aircraft/$id': typeof AircraftIdRoute
  '/conflicts/$id': typeof ConflictsIdRoute
  '/nations/$id': typeof NationsIdRoute
  '/squadrons/$id': typeof SquadronsIdRoute
  '/weapons/$id': typeof WeaponsIdRoute
  '/aces': typeof AcesIndexRoute
  '/aircraft': typeof AircraftIndexRoute
  '/conflicts': typeof ConflictsIndexRoute
  '/nations': typeof NationsIndexRoute
  '/squadrons': typeof SquadronsIndexRoute
  '/weapons': typeof WeaponsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/aces/$id': typeof AcesIdRoute
  '/aircraft/$id': typeof AircraftIdRoute
  '/conflicts/$id': typeof ConflictsIdRoute
  '/nations/$id': typeof NationsIdRoute
  '/squadrons/$id': typeof SquadronsIdRoute
  '/weapons/$id': typeof WeaponsIdRoute
  '/aces/': typeof AcesIndexRoute
  '/aircraft/': typeof AircraftIndexRoute
  '/conflicts/': typeof ConflictsIndexRoute
  '/nations/': typeof NationsIndexRoute
  '/squadrons/': typeof SquadronsIndexRoute
  '/weapons/': typeof WeaponsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quiz'
    | '/aces/$id'
    | '/aircraft/$id'
    | '/conflicts/$id'
    | '/nations/$id'
    | '/squadrons/$id'
    | '/weapons/$id'
    | '/aces/'
    | '/aircraft/'
    | '/conflicts/'
    | '/nations/'
    | '/squadrons/'
    | '/weapons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/quiz'
    | '/aces/$id'
    | '/aircraft/$id'
    | '/conflicts/$id'
    | '/nations/$id'
    | '/squadrons/$id'
    | '/weapons/$id'
    | '/aces'
    | '/aircraft'
    | '/conflicts'
    | '/nations'
    | '/squadrons'
    | '/weapons'
  id:
    | '__root__'
    | '/'
    | '/quiz'
    | '/aces/$id'
    | '/aircraft/$id'
    | '/conflicts/$id'
    | '/nations/$id'
    | '/squadrons/$id'
    | '/weapons/$id'
    | '/aces/'
    | '/aircraft/'
    | '/conflicts/'
    | '/nations/'
    | '/squadrons/'
    | '/weapons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizRoute: typeof QuizRoute
  AcesIdRoute: typeof AcesIdRoute
  AircraftIdRoute: typeof AircraftIdRoute
  ConflictsIdRoute: typeof ConflictsIdRoute
  NationsIdRoute: typeof NationsIdRoute
  SquadronsIdRoute: typeof SquadronsIdRoute
  WeaponsIdRoute: typeof WeaponsIdRoute
  AcesIndexRoute: typeof AcesIndexRoute
  AircraftIndexRoute: typeof AircraftIndexRoute
  ConflictsIndexRoute: typeof ConflictsIndexRoute
  NationsIndexRoute: typeof NationsIndexRoute
  SquadronsIndexRoute: typeof SquadronsIndexRoute
  WeaponsIndexRoute: typeof WeaponsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weapons/': {
      id: '/weapons/'
      path: '/weapons'
      fullPath: '/weapons/'
      preLoaderRoute: typeof WeaponsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squadrons/': {
      id: '/squadrons/'
      path: '/squadrons'
      fullPath: '/squadrons/'
      preLoaderRoute: typeof SquadronsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nations/': {
      id: '/nations/'
      path: '/nations'
      fullPath: '/nations/'
      preLoaderRoute: typeof NationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicts/': {
      id: '/conflicts/'
      path: '/conflicts'
      fullPath: '/conflicts/'
      preLoaderRoute: typeof ConflictsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aircraft/': {
      id: '/aircraft/'
      path: '/aircraft'
      fullPath: '/aircraft/'
      preLoaderRoute: typeof AircraftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aces/': {
      id: '/aces/'
      path: '/aces'
      fullPath: '/aces/'
      preLoaderRoute: typeof AcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weapons/$id': {
      id: '/weapons/$id'
      path: '/weapons/$id'
      fullPath: '/weapons/$id'
      preLoaderRoute: typeof WeaponsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squadrons/$id': {
      id: '/squadrons/$id'
      path: '/squadrons/$id'
      fullPath: '/squadrons/$id'
      preLoaderRoute: typeof SquadronsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nations/$id': {
      id: '/nations/$id'
      path: '/nations/$id'
      fullPath: '/nations/$id'
      preLoaderRoute: typeof NationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicts/$id': {
      id: '/conflicts/$id'
      path: '/conflicts/$id'
      fullPath: '/conflicts/$id'
      preLoaderRoute: typeof ConflictsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aircraft/$id': {
      id: '/aircraft/$id'
      path: '/aircraft/$id'
      fullPath: '/aircraft/$id'
      preLoaderRoute: typeof AircraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aces/$id': {
      id: '/aces/$id'
      path: '/aces/$id'
      fullPath: '/aces/$id'
      preLoaderRoute: typeof AcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizRoute: QuizRoute,
  AcesIdRoute: AcesIdRoute,
  AircraftIdRoute: AircraftIdRoute,
  ConflictsIdRoute: ConflictsIdRoute,
  NationsIdRoute: NationsIdRoute,
  SquadronsIdRoute: SquadronsIdRoute,
  WeaponsIdRoute: WeaponsIdRoute,
  AcesIndexRoute: AcesIndexRoute,
  AircraftIndexRoute: AircraftIndexRoute,
  ConflictsIndexRoute: ConflictsIndexRoute,
  NationsIndexRoute: NationsIndexRoute,
  SquadronsIndexRoute: SquadronsIndexRoute,
  WeaponsIndexRoute: WeaponsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
